### PR TITLE
Waits for completion added to run once command

### PR DESCRIPTION
**Pull request by michalzelechowski-getindata**
It requires timeout to be defined at CLI level.

### CODE REVIEW

**Comment by michalzelechowski-getindata** [comment]
Do you think it's a good idea for the plugin to show some output while running (f.e. in this case progress of active checks?)

**Comment by em-pe** [comment]
@michalzelechowski-getindata sounds like a good idea, but let's use `logging` for that, this way it can be easily turned on / off

**Comment by szczeles** [comment]
From my perspective there is no such need, this flag will be rarely used if the plugin is invoked by CI/CD - no need to keep CI/CD worker running while Airflow executes the pipeline.

**Review by szczeles — APPROVED** [review]

**Review by em-pe — APPROVED** [review]

**Comment by michalzelechowski-getindata** [comment]
Closing #26

**Pull request merged**
